# Generated by Django 5.2 on 2025-04-10 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(max_length=99, verbose_name='Страна')),
                ('city', models.CharField(max_length=99, verbose_name='Город')),
                ('street', models.CharField(max_length=99, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=9, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'контактные данные',
                'verbose_name_plural': 'контактные данные',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Название')),
                ('model', models.CharField(blank=True, max_length=254, null=True, verbose_name='Модель')),
                ('release_date', models.DateField(verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SupplyChainMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Название участника сети продаж')),
                ('type', models.CharField(choices=[('factory', 'Завод'), ('retail', 'Розничная сеть'), ('entrepreneur', 'Индивидуальный предприниматель')], max_length=30, verbose_name='Тип участника')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Задолженность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_chain_member', to='electronics_network.contactinfo', verbose_name='Контактные данные')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_chain_members', to='electronics_network.supplychainmember', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'участник цепочки поставок',
                'verbose_name_plural': 'участники цепочки поставок',
                'ordering': ('id',),
            },
        ),
    ]
