# Generated by Django 5.2 on 2025-04-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_network', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplychainmember',
            name='contact',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='network_member',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='electronics_network.supplychainmember', verbose_name='Участник'),
            preserve_default=False,
        ),
    ]
